
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    sendfile on;

    server {
        listen 80;
        server_name fale-com-a-missao.com.br www.fale-com-a-missao.com.br;
        
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://fale-com-a-missao.com.br$request_uri;
        }
    }
}
